penapi: 3.0.0
info:
  title: Youtube Statistics API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /videoid:
    get:
      summary: Returns stats for the give video id.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: JSON document with stats for the video
          content:
            application/json:
              schema: 
                type: object
             